apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  type: NodePort
  selector:
    app: trivial-go-web-app
  ports:
    - nodePort: 31004
      protocol: TCP
      port: 8080
